# Generated by Django 5.0.6 on 2024-06-06 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_company_contacts_company_employees_and_more'),
        ('contacts', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='contact_locations', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='company_employees', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='home',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_home', to='locations.location'),
        ),
    ]
