# Generated by Django 5.0.6 on 2024-06-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_company_contacts_company_employees_and_more'),
        ('contacts', '0002_contact_locations_alter_contact_companies_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='company_locations', to='companies.company'),
        ),
        migrations.AddField(
            model_name='location',
            name='inhabitants',
            field=models.ManyToManyField(blank=True, related_name='location_inhabitants', to='contacts.contact'),
        ),
    ]
